#+title: "Cost of Living" Review: Loneliness Hits Everyone
#+subtitle: If nobody got me, I know Majok got me. Can I get an AMEN?
#+description: Review of the Martyna Majok's play, "Cost of Living". To be honest, it was my attempt to earn a few extra credits for my English Drama class, but it ended up making me yap this hard.
#+date: <2024-10-30 Wed>
#+language: en

Everyone has their own ups and downs from time to time, and often with the downs comes loneliness.
Then, with loneliness comes vulnerability, which in turn makes one long for the attention and care of others.
Without this desire satisfied, loneliness takes the wheel again.
It is, in a way, an emotional death spiral that can only be corrected by the presence of others.

Characters from Martyna Majok's /Cost of Living/ are no exception to this.
The play follows the interactions between two disabled individuals and their caregivers.
Eddie, a middle-aged ex-trucker who recently lost his job due to a DUI incident, takes care of his quadriplegic wife, Anna.
Meanwhile, Jess, a Princeton-graduate first-generation immigrant living from hand to mouth, is employed by John, a wealthy Ph.D. candidate at Princeton with cerebral palsy.
Disabled or not, they all yearn for human companionship.

This was one of the most interesting parts of the play to me.
It is unimportant whether a person has a disability or not; they all feel loneliness like everyone else does.
Everyone knows this for fact: it is so obvious that it feels repetitive sometimes.
However, when I was following along the characters' interactions, I came to the painful realization that, deep down, I was treating the disabled people as different people---someone /foreign/ to me.

Instead, Anna is a regular Jersey lady full of sarcasm dealing with dysfunctional marriage.
John is an arrogant (somewhat, but rightfully so) Ph.D. student, probably growing salty by day because of the mountain of rejected manuscripts.
By the curtain call, they were regular people trying their best to escape from the melancholic death spiral, just like me.

Another part that caught my eye was the set design.[fn:1]
While both pairs share the same physical space on the set, I noticed that each pair occupies different parts of the set.
The left side of the set, where the dull-looking armchair and several boxes are arbitrarily laid out, is Anna and Eddie's area.
The opposite side, where a well-kept fish tank and spotless shower room tiled with white porcelain are visible, is John and Jess's area.

The placement and the quality of the props obviously reflect both pairs' financial and emotional conditions---a visual metaphor, if you will.
The initial state of Anna and Eddie's apartment is cluttered with unorganized boxes, symbolizing the dwindling relationship of the couple.
The reason for their imminent divorce is hinted by the brown, grimy armchair---just like the poorly-aged armchair, their marriage has gone stagnant long time ago.
On the other hand, John's apartment is kept pristine---a bit /too/ pristine, perhaps.
The blue fish tank, while the plants inside seem healthy and extremely well lit from an LED fixture, lacks any fish.
It might be a necessary choice from the production team as it would be hard to keep a school of fish in a tank healthy in transport, but to me it feels as if it represents the sense of emptiness in John.
Still, every part of John's apartment is placed in precise positions and looks new.
Combined with the fact that John has hard time using such fixtures on his own, the artificially clean room represents that John and his caregiver, Jess, lacks a genuine connection.

The last thing I want to touch on is the tilted clock.
There is a large pillar in the middle where all four characters interact in some way, making it a form of "shared space".
A clock is hung on the pillar at a 45 degree angle to the left.[fn:2]
Just as a tilted clock (if the hour markers are not numbers) can give an incorrect time to the viewers, the acts of /Cost of Living/ are nonlinear.
The play starts with Eddie's conversation with the audience at the bar and travels back in time to the two pairs' encounter.
Then, at the end, the play catches up from the end of the first act, where Eddie returns home from the bar.
While the technique of nonlinear storytelling itself sets up clever traps that trick the audience to expect more cliched plot, the chronologically fragmented narratives reflect the emotional turmoil caused by loneliness and the feeling of loss.
The tilted clock serves as another hint to the audience that it is not only us (the audience) feeling disoriented but also the characters in the play.

In conclusion, Martyna Majok's /Cost of Living/ masterfully explores the theme of loneliness and companionship through its rich characters, and these themes are highlighted by the production's thoughtful set design.
This play is not merely a story about disability; it is a story of individuals craving a genuine connection with other individuals.
No matter the circumstances, existence inevitably leads to loneliness of any form, and loneliness turns into a desperate need for connection.
It is a feeling all of us can relate to.
As the curtain fell (figuratively, because the theater didn't have one), I found myself contemplating the moments of desperation I experienced.
Then, I realized that the connections I often take for granted were, in fact, supporting me since the beginning.
/Cost of Living/ serves as a great reminder to all of us of the importance of recognizing one's loneliness and, more importantly, the importance of /being there/ for one another.

[fn:1] Yes, Professor Lee /did/ remind me to take a note of the set design before the play. I owe her an apology, though; I may have gotten a bit carried away and written well past the 300-word limit. My sincere apologies! I just wanted to post this review online (most likely my blog) later, so I hope you'll forgive my little ramble.

[fn:2] Full disclosure: /this/ was the thing Professor Lee wanted me to take notes of.
