#+title: 키보토스교직원노동조합 성명서
#+subtitle: 윤석열 대통령 탄핵에 관하여
#+description: 12월 3일, 국회 앞에 구름처럼 몰려든 사람들과 그 머리 위를 날아다니는 헬리콥터 소리를 아직도 똑똑히 기억합니다. 함께 싸운 모든 분들에게 감사를 전하며 이 글을 씁니다.
#+date: <2024-12-14 Sat>
#+language: ko

블루 아카이브는 청춘의 이야기입니다. 즐거운 일상을 함께 공유하고 찬란한 청춘을 함께 향유하며 눈부신 성장을 함께 기뻐하는, 모든 순간의 「아카이브」입니다.

그 이야기에서 플레이어는—우리는—선생님입니다. 단지 학문만을 가르치는 선생님이 아니라, 몸소 책임을 다하고 자신을 희생하여 학생들을 올바른 길로 인도하는 선생님입니다.
동시에 우리는 길 잃은 학생들이 언제든지 돌아올 수 있는 믿음직한 쉼터이기도 합니다.
블루 아카이브에서 우리는 누가 뭐라 해도 어엿한 어른이고, 떳떳한 어른입니다.

한 나라를 보살피는 국정 종사자들, 특히나 대통령과 같은 고위 공직자들은 그러한 어른이어야 합니다.
국민의 목소리를 듣고 나라라는 공동체를 이끌며, 국민이 힘들 때 기댈 수 있는 보루여야 합니다.

그런데 현실은 어떠하였습니까? 대통령이라는 자가 권력을 지키겠다는 알량한 욕심에 계엄을 선언하여 수많은 국민을 공포—​/테러/​—로 몰아넣지 않았습니까?
국무총리를 포함한 다른 고위 공직자들은 그러한 자를 비호하고자 궤변을 늘어놓지 않았습니까?
이들을 두고 좋은 어른이라 부를 수 있습니까?
책임을 망각하고 공포로 타인을 지배하고자 하는 자가 과연 어른입니까?

플레이어로서, 선생님으로서 우리는 학생의 고통에 분노하고 학생을 억압하는 불의와 대적하며 학생들의 미소를 지켜냅니다.
오늘 저는 이야기 속의 제가 그러하였듯, 사람들의 고통에 분노하였고, 국민을 억압하는 불의와 대적하였으며 모두와 함께 민주주의를 지켜내었습니다.

키보토스에는 여러 선생님이 있습니다.
남성 선생님이 있는가 하면 여성 선생님도 있고, 그 사이 어딘가에 위치한 선생님도 있습니다.
어린 선생님도, 나이 지긋한 선생님도 있고, 키가 작은 분도, 큰 분도 있겠지요.
살집이 있는 분도, 그렇지 않은 분도 있을 것입니다.
서로 다른 모습을 가진 우리지만, 아로나가 빨간 펜으로 슥슥 그린 서툰 초상화 아래에서만큼은 우리 모두 학생 모두가 존경하는 선생님이 됩니다.

키보토스에 계신 선생님 여러분, 그리고 키보토스에 계시지 않은 선생님 여러분.
우리는 함께 싸워 우리에게 소중한 것을 지켜내었고, 우리가 사랑하는 이들에게 떳떳한 어른이 되었습니다.
싸움에 참여해주신 모든 분들과 도움을 주신 모든 분들에게 감사 인사를 드립니다.

언젠가 키보토스에서 다시 만나기를 고대하고 있겠습니다.

키보토스교직원노동조합 \\
총학생회지부 샬레특별지회 기수,

랭호 드림.
